[package]
name = "db"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.3"
kvdb-rocksdb = {path="./src/kvdb-rocksdb"}
kvdb = {git="https://github.com/paritytech/parity-common.git", branch="ao-upstream-rocksdb", version = "0.2"}